server:
  port: 8080
spring:
  application:
    name: pay
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pay
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 5
url:
  return: http://zfbzf.free.idcfengye.com/cg
  notify: http://zfbzf.free.idcfengye.com/yb